from time import sleep 
print(" *  *  *  *  *\n ** ** ** ** **")
sleep(1)
print("|| || || || ||")
sleep(1)
print("==================")
print("H", end="")
sleep(1)
print("a",end="")
sleep(1)
print("p",end="")
sleep(1)
print("p",end="")
sleep(1)
print("y",end="")
sleep(1)
print(" ", end="")
print("B",end="")
sleep(1)
print("i",end="")
sleep(1)
print("r",end="")
sleep(1)
print("t",end="")
sleep(1)
print("h",end="")
sleep(1)
print("d",end="")
sleep(1)
print("a",end="")
sleep(1)
print("y",end="")
sleep(1)
print(" ", end="")
print("Toria", end="")
sleep(1)
print("")
print("---------------------")
sleep(2)
print("May God Bless You!!")
sleep(1)
print("!!!!!!!!!!!!!!!!!!!!!")
print(" ")
sleep(1)
print("From: Rossi")
 